import React, { useState, useEffect } from 'react';
import { Search, ChevronDown, SlidersHorizontal, ChevronLeft, ChevronRight, Shield } from 'lucide-react';
import html2pdf from 'html2pdf.js';

export default function Logs() {
  const [logs, setLogs] = useState([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [riskFilter, setRiskFilter] = useState('ALL');
  const [sortBy, setSortBy] = useState('NEWEST');
  
  useEffect(() => {
    const fetchLogs = async () => {
      try {
        const userId = localStorage.getItem('userId');
        const role = localStorage.getItem('userRole');
        const adminPrefix = role === 'admin' ? 'admin/' : '';
        const userSuffix = role === 'admin' ? '' : `/${userId}`;
        const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';
        const res = await fetch(`${API_BASE_URL}/${adminPrefix}history${userSuffix}`);
        const data = await res.json();
        setLogs(Array.isArray(data) ? data : []);
      } catch (err) {
        console.error('Failed to fetch logs automatically.', err);
      }
    };
    fetchLogs();
  }, []);

  const filteredLogs = logs
    .filter(log => {
      const username = log.userId?.username?.toLowerCase() || '';
      return username.includes(searchTerm.toLowerCase());
    })
    .filter(log => riskFilter === 'ALL' ? true : log.risk === riskFilter)
    .sort((a, b) => {
      const da = new Date(a.createdAt).getTime();
      const db = new Date(b.createdAt).getTime();
      return sortBy === 'NEWEST' ? db - da : da - db;
    });

  const totalLogs = logs.length;
  const realCount = logs.filter(l => l.status === 'REAL').length;
  const highThreatCount = logs.filter(l => l.risk === 'HIGH').length;
  const authenticityRate = totalLogs > 0 ? ((realCount / totalLogs) * 100).toFixed(1) + '%' : '0.0%';

  const handleDownloadPdf = () => {
    const htmlContent = `
      <div style="font-family: Arial, sans-serif; background-color: white; color: black; padding: 20px;">
        <h2 style="text-align: center; margin-bottom: 24px; text-transform: uppercase;">DeepShield Automated Threat Report</h2>
        <table style="width: 100%; border-collapse: collapse; font-size: 12px; text-align: left;">
          <thead>
            <tr>
              <th style="border: 1px solid black; padding: 8px;">Username</th>
              <th style="border: 1px solid black; padding: 8px;">File Name</th>
              <th style="border: 1px solid black; padding: 8px;">Status</th>
              <th style="border: 1px solid black; padding: 8px;">Risk Level</th>
              <th style="border: 1px solid black; padding: 8px;">Timestamp</th>
            </tr>
          </thead>
          <tbody>
            ${filteredLogs.map(log => `
              <tr>
                <td style="border: 1px solid black; padding: 8px;">${log.userId?.username || 'Unknown User'}</td>
                <td style="border: 1px solid black; padding: 8px;">${log.fileId?.fileName || 'Unidentified'}</td>
                <td style="border: 1px solid black; padding: 8px; font-weight: bold;">${log.status}</td>
                <td style="border: 1px solid black; padding: 8px;">${log.risk}</td>
                <td style="border: 1px solid black; padding: 8px;">${new Date(log.createdAt).toLocaleString()}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
        <div style="margin-top: 30px; font-size: 10px; color: gray; text-align: center;">
          Document generated by DeepShield Core Instance at ${new Date().toLocaleString()}
        </div>
      </div>
    `;

    const opt = {
      margin:       0.5,
      filename:     `DeepShield_Scan_Report_${new Date().getTime()}.pdf`,
      image:        { type: 'jpeg', quality: 0.98 },
      html2canvas:  { scale: 2 },
      jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }
    };

    html2pdf().set(opt).from(htmlContent).save();
  };

  return (
    <div id="logs-report-content" className="flex flex-col gap-6 w-full pb-8">
      {/* Header */}
      <div className="flex justify-between items-start mb-6">
        <div>
          <h1 className="text-3xl font-bold text-white tracking-tight leading-none mb-2">Activity Logs</h1>
          <p className="text-ds-muted text-sm max-w-xl leading-relaxed mt-4">
            Real-time surveillance data and cryptographic verification streams for the Terminal Elite infrastructure.
          </p>
        </div>
        <div className="text-right flex flex-col items-end">
          <div className="text-[10px] uppercase font-bold tracking-widest text-ds-muted mb-2">Live Status</div>
          <div className="bg-[#162719] border border-ds-border rounded-full px-3 py-1 flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-ds-accent animate-pulse"></span>
            <span className="text-[10px] font-bold tracking-widest uppercase text-ds-accent text-opacity-80">Monitoring Active</span>
          </div>
        </div>
      </div>

      {/* Main Content Area */}
      <div className="bg-ds-card rounded-xl border border-ds-border flex flex-col overflow-hidden">
        {/* Toolbar */}
        <div className="p-4 border-b border-ds-border flex gap-4">
          <div className="relative flex-1">
            <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-ds-muted" />
            <input 
              type="text" 
              placeholder="Search by username..." 
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full bg-[#121622] rounded-md py-2.5 pl-9 pr-4 text-sm text-ds-muted outline-none border border-transparent focus:border-ds-border"
            />
          </div>
          
          <div className="relative">
            <select
              value={riskFilter}
              onChange={(e) => setRiskFilter(e.target.value)}
              className="bg-[#121622] border border-transparent hover:border-ds-border appearance-none px-4 py-2.5 rounded-md flex items-center gap-6 text-sm text-ds-text w-[180px] outline-none transition-colors cursor-pointer"
            >
              <option value="ALL">All Risk Levels</option>
              <option value="HIGH">High Risk</option>
              <option value="MEDIUM">Medium Risk</option>
              <option value="LOW">Low Risk</option>
            </select>
            <ChevronDown className="w-4 h-4 text-ds-muted absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none" />
          </div>
          
          <div className="relative">
            <select
              value={sortBy}
              onChange={(e) => setSortBy(e.target.value)}
              className="bg-[#121622] border border-transparent hover:border-ds-border appearance-none px-4 py-2.5 rounded-md flex items-center gap-6 text-sm text-ds-text w-[200px] outline-none transition-colors cursor-pointer"
            >
              <option value="NEWEST">Sort by Time (Newest)</option>
              <option value="OLDEST">Sort by Time (Oldest)</option>
            </select>
            <ChevronDown className="w-4 h-4 text-ds-muted absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none" />
          </div>
          
          <button className="bg-[#121622] border border-transparent hover:border-ds-border w-10.5 px-3 py-2.5 rounded-md flex items-center justify-center text-ds-muted transition-colors">
            <SlidersHorizontal className="w-4 h-4" />
          </button>
        </div>

        {/* Table */}
        <div className="flex-1 overflow-x-auto">
          <table className="w-full text-left border-collapse min-w-[800px]">
            <thead>
              <tr className="text-[10px] uppercase tracking-widest text-white/50 font-bold border-b border-ds-border">
                <th className="p-4 pl-6 font-bold py-5">Username</th>
                <th className="p-4 font-bold py-5">File Name</th>
                <th className="p-4 font-bold py-5">Status</th>
                <th className="p-4 font-bold py-5">Risk Level</th>
                <th className="p-4 pr-6 font-bold py-5 text-right">Timestamp</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-ds-border text-sm">
              {filteredLogs.map((log, i) => (
                <tr key={i} className="hover:bg-ds-dark/40 transition-colors">
                  <td className="p-4 pl-6">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-full bg-[#2a3441] text-xs font-bold flex items-center justify-center text-white/80 shrink-0">
                        {log.userId?.username ? log.userId.username[0].toUpperCase() : 'U'}
                      </div>
                      <span className="text-white font-medium">{log.userId?.username || 'Unknown User'}</span>
                    </div>
                  </td>
                  <td className="p-4 font-mono text-ds-muted text-xs">{log.fileId?.fileName || 'Unidentified Payload'}</td>
                  <td className="p-4">
                    <span className={`inline-flex px-2 py-0.5 text-[9px] font-bold uppercase tracking-widest rounded ${
                      log.status === 'FAKE' ? 'bg-[#3b1c20] text-[#ef4444] border border-[#ef4444]/20' : 
                      log.status === 'SUSPICIOUS' ? 'bg-[#1e1b4b] text-blue-400 border border-blue-400/20' :
                      'bg-[#18311d] text-ds-accent border border-ds-accent/20'
                    }`}>
                      {log.status}
                    </span>
                  </td>
                  <td className="p-4">
                    <div className="flex items-center gap-2">
                       <span className={`w-2 h-2 rounded-full ${
                          log.risk === 'HIGH' ? 'bg-[#ef4444]' : 
                          log.risk === 'MEDIUM' ? 'bg-blue-400' : 'bg-ds-accent'
                       }`}></span>
                       <span className="text-white/80 font-bold text-xs">{log.risk}</span>
                    </div>
                  </td>
                  <td className="p-4 pr-6 font-mono text-ds-muted text-right text-xs">
                    {new Date(log.createdAt).toLocaleString()}
                  </td>
                </tr>
              ))}
              {filteredLogs.length === 0 && (
                <tr>
                  <td colSpan="5" className="p-8 text-center text-ds-muted italic text-sm">
                     No scan histories found matching your filter parameters.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>

        {/* Pagination Footer */}
        <div className="p-4 px-6 border-t border-ds-border flex items-center justify-between">
          <div className="text-[10px] font-bold tracking-widest uppercase text-ds-muted">
            Showing {filteredLogs.length} events
          </div>
          <div className="flex gap-4 items-center">
            <button className="text-ds-muted hover:text-white transition-colors opacity-50 cursor-not-allowed">
              <ChevronLeft className="w-5 h-5" />
            </button>
            <button className="text-white hover:text-ds-accent transition-colors">
              <ChevronRight className="w-5 h-5" />
            </button>
          </div>
        </div>
      </div>

      {/* Bottom Layout Row */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Integrity Summary */}
        <div className="md:col-span-2 bg-ds-card rounded-xl border border-ds-border p-6 flex flex-col relative overflow-hidden">
          <Shield className="absolute -right-6 -bottom-10 w-48 h-48 text-white/5 pointer-events-none" />
          <h3 className="text-white font-bold text-lg mb-6 z-10">Integrity Summary</h3>
          <div className="flex gap-4 lg:gap-8 z-10">
            <div className="bg-[#0b0e14] rounded-lg p-5 flex-1 border border-transparent">
              <div className="text-[10px] font-bold tracking-widest uppercase text-ds-muted mb-2">Total Logs</div>
              <div className="text-3xl font-bold text-white tracking-tighter">{totalLogs}</div>
            </div>
            <div className="bg-[#0b0e14] rounded-lg p-5 flex-1 border border-transparent">
              <div className="text-[10px] font-bold tracking-widest uppercase text-ds-muted mb-2">Authenticity Rate</div>
              <div className="text-3xl font-bold text-ds-accent tracking-tighter">{authenticityRate}</div>
            </div>
            <div className="bg-[#0b0e14] rounded-lg p-5 flex-1 border-l-2 border-l-[#ef4444]">
              <div className="text-[10px] font-bold tracking-widest uppercase text-white/50 mb-2">Active Threats</div>
              <div className="text-3xl font-bold text-[#ef4444] tracking-tighter">{highThreatCount}</div>
            </div>
          </div>
        </div>

        {/* Automated Report */}
        <div className="bg-ds-accent rounded-xl p-6 flex flex-col justify-between">
          <div>
            <h3 className="text-ds-dark font-bold text-lg mb-2">Automated Report</h3>
            <p className="text-ds-dark/70 text-sm max-w-[90%] leading-relaxed mb-6">
              Generate a cryptographic summary of last 24h activity.
            </p>
          </div>
          <button 
            onClick={handleDownloadPdf}
            className="w-full bg-[#1f300c] hover:bg-black/90 text-ds-accent font-bold py-3.5 rounded text-sm tracking-widest uppercase transition-colors border border-black/20"
          >
            Compile Data
          </button>
        </div>
      </div>
    </div>
  );
}
